<?php

declare(strict_types=1);

namespace Tests\Contract\Support;

use Illuminate\Container\Container;
use Illuminate\Routing\Route as IlluminateRoute;
use Illuminate\Support\Facades\Route;
use Symfony\Component\Yaml\Yaml;

/**
 * Reads `docs/openapi.yaml` and the live route table, and hands both to the tests
 * as plain arrays.
 *
 * ## Why this exists rather than a hard-coded fixture
 *
 * The whole point of a conformance suite is that the assertions are DERIVED from
 * the published document. A test file that typed `"SuccessEnvelope"` into an
 * expectation would be asserting the author's memory of the contract, not the
 * contract, and it would keep passing after the generator changed the envelope.
 * Everything below is read at run time: the operation list, the documented
 * statuses, and the `$ref` each status carries. Change `docs/openapi.yaml` and
 * these tests change behaviour without being edited.
 *
 * ## The document is parsed, not trusted
 *
 * `docs/openapi.yaml` is generated by todo 53's `sehatly:openapi` and had never
 * been checked against the running application when this todo started. Nothing
 * here assumes it is correct: {@see liveOperations()} reads
 * `Route::getRoutes()` instead, so a disagreement between the two is visible as
 * a test failure rather than as a silent rubber stamp.
 *
 * ## Why the YAML parser is `symfony/yaml` and not `opis/json-schema`
 *
 * The plan's todo 49 text named `opis/json-schema ^2.4`. It is **not** in
 * `composer.json` and `vendor/opis` does not exist on this checkout, so adding it
 * would mean a network install inside a todo whose guardrails forbid touching the
 * dependency set. `symfony/yaml` IS present -- it is a hard dependency of
 * `laravel/framework` -- and it is used to read the document.
 *
 * Response validation is then done by {@see EnvelopeValidator}, which
 * implements the JSON Schema draft 2020-12 SUBSET the generated envelopes
 * actually use. That subset is listed in full on that class, because "we wrote
 * our own validator" is only acceptable if the subset is named rather than
 * implied. For this document it is complete: every keyword the five envelope
 * schemas use is implemented, and {@see EnvelopeValidator::unsupportedKeywords()}
 * fails the suite if a future regeneration introduces one this validator would
 * silently ignore. A validator that silently ignores a keyword is how a
 * conformance suite starts lying.
 */
final class ContractSpec
{
    /**
     * The HTTP methods that can appear as an operation key under a path.
     *
     * OpenAPI 3.1 permits `get`, `put`, `post`, `delete`, `options`, `head`,
     * `patch` and `trace`. `HEAD` is excluded from the LIVE side because Laravel
     * registers it implicitly for every `GET` route; treating it as a real
     * operation would report 74 phantom routes that the document correctly does
     * not publish.
     */
    private const HTTP_METHODS = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'];

    /**
     * The lazily-parsed document. Parsed once per process.
     *
     * @var array<string, mixed>|null
     */
    private static ?array $document = null;

    /**
     * The whole parsed `docs/openapi.yaml`.
     *
     * @return array<string, mixed>
     */
    public static function document(): array
    {
        if (self::$document === null) {
            $path = self::projectRoot().'/docs/openapi.yaml';

            if (! is_file($path)) {
                throw new \RuntimeException(
                    'docs/openapi.yaml is missing. Run `php artisan sehatly:openapi` to generate it.',
                );
            }

            $parsed = Yaml::parseFile($path);

            if (! is_array($parsed)) {
                throw new \RuntimeException('docs/openapi.yaml did not parse into an array.');
            }

            self::$document = $parsed;
        }

        return self::$document;
    }

    /**
     * The project root, resolvable with or without a booted application.
     *
     * `base_path()` needs a bound container, and Pest resolves a dataset closure
     * during test COLLECTION -- before `createApplication()` has run for the first
     * test. A dataset that read the document through `base_path()` therefore died
     * with `Call to undefined method Illuminate\Container\Container::basePath()`
     * on the very first data set rather than on the assertion it was written to
     * reach. So the container is used when it is available and the directory
     * layout is walked when it is not.
     *
     * `__DIR__` is `tests/Contract/Support`, so three levels up is the project
     * root. That is the same relationship `composer.json`'s `autoload-dev`
     * psr-4 map declares (`Tests\` -> `tests/`), so the two cannot disagree.
     */
    private static function projectRoot(): string
    {
        $container = Container::getInstance();

        if ($container !== null && $container->has('path.base')) {
            return rtrim((string) $container->make('path.base'), '/\\');
        }

        return dirname(__DIR__, 3);
    }

    /**
     * Every operation the document publishes, keyed `"METHOD /path"`.
     *
     * @return array<string, array<string, mixed>>
     */
    public static function specOperations(): array
    {
        $operations = [];

        foreach (self::document()['paths'] ?? [] as $path => $item) {
            foreach (self::HTTP_METHODS as $method) {
                if (isset($item[$method]) && is_array($item[$method])) {
                    $operations[$method.' '.$path] = $item[$method];
                }
            }
        }

        ksort($operations);

        return $operations;
    }

    /**
     * Every `/api/v1` operation the RUNNING application has registered.
     *
     * Read from `Route::getRoutes()` rather than from `routes/api.php`, because
     * the route table is what actually answers a request. A route commented out
     * of the file but still registered would be caught; a route added to the file
     * but never registered would be caught too.
     *
     * @return array<string, array<string, mixed>>
     */
    public static function liveOperations(): array
    {
        $operations = [];

        foreach (Route::getRoutes() as $route) {
            $uri = $route->uri();

            if (! str_starts_with($uri, 'api/v1')) {
                continue;
            }

            $path = '/'.ltrim($uri, '/');

            foreach ($route->methods() as $method) {
                // `HEAD` is registered implicitly for every `GET` and is not an
                // operation the document publishes.
                if ($method === 'HEAD') {
                    continue;
                }

                $operations[strtolower($method).' '.$path] = [
                    'name' => $route->getName(),
                    'action' => $route->getActionName(),
                    'middleware' => self::routeLevelMiddleware($route),
                ];
            }
        }

        ksort($operations);

        return $operations;
    }

    /**
     * The route's OWN middleware names, with the `api` group removed.
     *
     * `gatherMiddleware()` returns the fully resolved stack, which always begins
     * with the group name `api` because `bootstrap/app.php` mounts these routes
     * through `withRouting(apiPrefix: 'api/v1')`. The document publishes the
     * per-route names (`auth:sanctum`, `permission:...`, `tipe:...`,
     * `throttle:...`), so the group name is stripped before comparison or the
     * check would fail on a string neither side ever wrote.
     *
     * @return list<string>
     */
    private static function routeLevelMiddleware(IlluminateRoute $route): array
    {
        return array_values(array_filter(
            $route->gatherMiddleware(),
            static fn (string $name): bool => $name !== 'api',
        ));
    }

    /**
     * The `$ref` a status publishes for one operation, or null.
     *
     * @param  array<string, mixed>  $operation
     */
    public static function schemaRefFor(array $operation, string $status): ?string
    {
        $schema = $operation['responses'][$status]['content']['application/json']['schema'] ?? null;

        if (! is_array($schema) || ! isset($schema['$ref'])) {
            return null;
        }

        return (string) $schema['$ref'];
    }

    /**
     * Resolve a `#/components/schemas/Name` pointer to its schema array.
     *
     * @return array<string, mixed>
     */
    public static function resolveRef(string $ref): array
    {
        $prefix = '#/components/schemas/';

        if (! str_starts_with($ref, $prefix)) {
            throw new \RuntimeException("Unsupported \$ref '{$ref}': this suite only resolves component schemas.");
        }

        $name = substr($ref, strlen($prefix));
        $schema = self::document()['components']['schemas'][$name] ?? null;

        if (! is_array($schema)) {
            throw new \RuntimeException("The document publishes no component schema named '{$name}'.");
        }

        return $schema;
    }

    /**
     * The statuses an operation documents, as strings, in the document's order.
     *
     * @param  array<string, mixed>  $operation
     * @return list<string>
     */
    public static function documentedStatuses(array $operation): array
    {
        return array_map(strval(...), array_keys($operation['responses'] ?? []));
    }

    /**
     * Whether an operation declares no security at all, or an empty one.
     *
     * Both mean "anonymous", and the document is explicit that an empty
     * `security: []` is a positive statement rather than an omission.
     *
     * @param  array<string, mixed>  $operation
     */
    public static function isAnonymous(array $operation): bool
    {
        if (! array_key_exists('security', $operation)) {
            return true;
        }

        return $operation['security'] === [];
    }
}